version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: twitter-like-api
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: twitter-like-api-db